config/routes.rb
Rails.application.routes.draw do
  resources :exit_types
  devise_for :users, path_prefix: 'app'
  resources :users

  resources :passwords, only: [:edit, :update]
  resources :facilities do
    resources :locations
  end
  resources :cohorts
  resources :cohort_imports, only: [:create, :new]
  resources :measurement_types
  resources :animals do
    collection do
      get '/csv_upload', action: 'csv_upload'
      post '/csv_upload', action: 'import'
    end
  end
  resources :enclosures do
    collection do
      get '/csv_upload', action: 'csv_upload'
      post '/csv_upload', action: 'import'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :measurements
  post '/file_uploads', to: 'file_uploads#upload'
  resources :file_uploads, only: [:index, :new, :destroy]
  get '/file_uploads/csv_index', to: 'file_uploads#csv_index', as: 'csv_index'
  get '/file_uploads/:id', to: 'file_uploads#show', as: 'show_processed_file'

  get '/file_uploads/errors/:id', to: 'file_uploads#show_processing_csv_errors', as: 'show_processing_csv_errors'

  # resources :reports, only: [:index] # Replaced by blazer reporting - 1/24/21

  resources :operations, only: [:index]

  get 'home', action: 'index', controller: 'home'
  get 'about', action: 'show', controller: 'home'

  # mount ReportsKit::Engine, at: '/' # Replaced by blazer reporting - 1/24/21

  authenticate :user do
    mount Blazer::Engine, at: "blazer", as: 'reports'
  end

  root 'home#index'
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  include OrganizationScope
  belongs_to :user
  has_one_attached :file

  validates_presence_of :status
end

app/controllers/file_uploads_controller.rb
# frozen_string_literal: true

# Controller manages uploading and displaying CSVs
class FileUploadsController < ApplicationController
  # The second value for each category entry will be used to determine the
  # job class that processes the data.
  #
  # Ex: Selecting "Measurement" in the form will post "Measurement"
  # and process the data with a MeasurementJob.
  before_action :set_processed_file, only: %i[show destroy]

  FILE_UPLOAD_CATEGORIES = CsvImporter::CATEGORIES.map do |category|
    [category, category.delete(' ')]
  end.freeze

  def index
    @pagy, @processed_files = pagy(ProcessedFile.for_organization(current_organization).order(updated_at: :desc))
    @processed_files.each { |processed_file| authorize! :index, processed_file }
  end

  def csv_index
    @pagy, @file_uploads = pagy(FileUpload.for_organization(current_organization).order(created_at: :desc))
  end

  def new
    @categories = [['Select One', '']] + FILE_UPLOAD_CATEGORIES
  end

  def show
    authorize! :show, @processed_file
    record_class = CsvImporter::CATEGORIES.find { |v| v == @processed_file.category }.constantize
    @headers = record_class::HEADERS
    @records = record_class.data_for_file(@processed_file.id)
    respond_to do |format|
      format.html
      format.csv { send_data @processed_file.temporary_file.contents, filename: @processed_file.filename }
    end
  end

  def upload
    @file_uploads = []

    input_files.each do |input_file|
      @file_uploads << FileUploader.new(
        category: params[:category],
        input_file: input_file,
        organization: current_organization
      ).process
    end
  rescue NoMethodError
    head :bad_request
  end

  def destroy
    authorize! :destroy, @processed_file
    if @processed_file.destroy
      redirect_to file_uploads_path, notice: 'File successfully deleted'
    else
      redirect_to file_uploads_path, alert: 'There was an issue deleting this file upload'
    end
  end

  private

  def set_processed_file
    @processed_file = ProcessedFile.find(params[:id])
  end

  def input_files
    params[:input_files]
  end
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
  def file_upload_status_style(status)
    if success? status
      'fa fa-check has-text-success'
    elsif pending? status
      'fas fa-spinner'
    elsif failed? status
      'fas fa-exclamation-triangle has-text-danger'
    end
  end

  def success?(status)
    status.include?('0 records had errors') || status == 'Processed'
  end

  def pending?(status)
    status.include?('Pending') || status == 'Running'
  end

  def failed?(status)
    status == 'Failed' || status.match(/[1-9]\d* records had errors/)
  end
end

app/views/file_uploads/csv_index.html.erb
<section class="h-screen bg-background p-12">
  <div class="container mx-auto bg-white py-6 px-8 rounded-md shadow-sm">
    <p id="notice"><%= notice %></p>

    <div class="flex justify-between items-center mb-4">
      <h1 class="text-title3 mb-4">File Uploads</h1>
    </div>

    <table class="table-auto w-full border" style="width: 100%">
      <colgroup>
        <col span="3">
        <col span="1" style="width: 5%;">
        <col span="1" style="width: 30%;">
      </colgroup>
      <thead>
      <tr class="border">
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">User</th>
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">File</th>
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">Created At</th>
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">Error</th>
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">Status</th>
      </tr>
      </thead>

      <tbody>
      <% @file_uploads.each do |upload| %>
        <tr>
          <td class="px-4 py-2"><%= upload.user.email %></td>
          <td class="px-4 py-2 text-primary-dark"><%= link_to upload.file.filename, rails_blob_path(upload.file, disposition: 'attachment') %></td>
          <td class="px-4 py-2"><%= upload.created_at.strftime('%Y-%m-%d %H:%M') %></td>
          <td class="px-4 py-2"><div class="<%= file_upload_status_style(upload.status) %>"></div></td>
          <td class="px-4 py-2"><%= upload.status %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

  <%== pagy_nav(@pagy) %>
  </div>
</section>

app/views/file_uploads/index.html.erb
<section class="h-screen bg-background p-12">
  <div class="container mx-auto bg-white py-6 px-8 rounded-md shadow-sm">
    <p id="notice"><%= notice %></p>
    <div class="flex justify-between items-center mb-4"><h1 class="text-title2 text-center">Uploaded Files</h1>
      <div class="flex items-center justify-center">
        <%= link_to new_file_upload_path do %>
          <button class="bg-primary-dark hover:bg-primary text-white font-bold py-2 px-4 rounded inline-flex items-center mr-4">
            <%= image_tag  "icons/plus.png", size: 17 %>
            <span class="ml-2 hidden md:block">Upload new file</span>
            <span class="ml-2 md:hidden">New</span>
          </button>
        <% end %>
      </div>
    </div>

    <table class="table-auto w-full border" style="width: 100%">
      <thead>
      <tr class="border">
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">File</th>
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">Category</th>
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">Created</th>
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">Status</th>
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">Error</th>
        <th class="text-sm text-caption-light font-medium px-4 py-2 uppercase" scope="col">Action</th>
      </tr>
      </thead>

      <tbody>
        <%- @processed_files.each do |pf| %>
          <tr>
            <td class="px-4 py-2 text-primary-dark text-center"> <%- if pf.job_stats["rows_not_imported"].to_i > 0 %>
              <%= link_to pf.filename, show_processing_csv_errors_path(pf.id) %>
              <% else %>
                <%= link_to pf.filename, show_processed_file_path(pf.id, format: :csv) %>
              <%- end %>
            </td>
            <td class="px-4 py-2"><%= pf.category %></td>
            <td class="px-4 py-2"><%= pf.created_at.strftime('%Y-%m-%d %H:%M') %></td>
            <td class="px-4 py-2 text-center"><div class="<%= file_upload_status_style(pf.status) %>"></div></td>
            <td class="px-4 py-2"><%= pf.job_errors %></td>
            <td class="px-4 py-2 text-center">
              <% if pf.status == 'Processed' %>
                <%= link_to 'Show', show_processed_file_path(pf.id) %>
              <% else %>
                <%= link_to image_tag("icons/trash.svg"), file_upload_path(pf), title: 'Delete', method: :delete, class: 'trash-ico' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <%== pagy_nav(@pagy) %>
  </div>
</section>

app/views/file_uploads/new.html.erb
<section class="px-6 py-12">
  <div class="container">
    <h1 class="text-title3 mb-4">File Upload</h1>

    <p class="break-words leading-tight mb-6 text-base">Select the type of spreadsheet and select up to 10 .xlsx or .csv spreadsheets. <br /> CSV files are recommended for large spreadsheets (over 1000 rows).</p>

    <%= form_tag({action: :upload}, multipart: true, method: 'post') do %>
      <div class="mb-3">
        <%= label_tag(:category, 'Category', class: 'font-bold') %>
        <div class="mt-2 relative text-left">
          <div class="align-top h-9 inline-block max-w-full relative">
            <%= select_tag(:category, options_for_select(@categories), required: true,
                class: 'border border-gray-400 border-solid cursor-pointer p-2 rounded') %>
          </div>
        </div>
      </div>

      <div class="mb-3">
        <div>
          <%= label_tag('input_files[]', 'Select up to 10 files to upload', class: 'font-bold') %>
          <%= file_field_tag 'input_files[]', multiple: true, required: true, class: 'block mt-2' %>
        </div>
      </div>

      <div class="flex justify-start mb-3">
        <div class="flex-shrink-0 mb-0 mr-3 relative text-left">
          <%= submit_tag('Submit',
              class: 'bg-purple-600 border border-transparent cursor-pointer font-medium px-4 py-1 rounded-sm text-white') %>
        </div>

        <div class="flex-shrink-0 mb-0 mr-3 relative text-left">
          <%= link_to 'Cancel', file_uploads_path,
              class: 'bg-gray-200 border border-transparent cursor-pointer inline-flex px-2 py-1 rounded-sm' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/file_uploads/show.html.erb
<section class="section">
  <div class="container is-fluid">
    <h1 class="text-title3 mb-4">Processed File</h1>
    <div class="columns">
      <div class="column is-1">
        File name:
      </div>
      <div class="column is-11">
        <%= @processed_file.filename %>
      </div>
    </div>
    <div class="columns">
      <div class="column is-1">
        Processed at:
      </div>
      <div class="column is-11">
        <%= @processed_file.updated_at %>
      </div>
    </div>
    <br />
    <div class="container_with_scroll">
      <table class="table is-bordered if-fullwidth is-striped is-hoverable">
        <thead>
        <%- @headers.each do |attr|%>
          <th><%= attr %></th>
        <%- end %>
        </thead>
        <tbody>
        <%- @records.each do |record| %>
          <tr>
            <%- record.display_data.each do |data_point|%>
              <td><%= data_point %></td>
            <%- end %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/file_uploads/show_processing_csv_errors.html.erb
<section class="section">
<div class="container is-fluid">
  <h1 class="text-title3 mb-4">Detailed processed file with errors</h1>

  <br />
  <%= link_to "<button class='button is-link'>Upload New File</button>".html_safe, new_file_upload_path %>
  <br />
  <br />
  Filename: <%= @processed_file.filename %> processed at <%= @processed_file.updated_at %><br />
  Processed At: <%= @processed_file.updated_at %><br />
  Category: <%= @processed_file.category %><br />
  Statistics: <%= @processed_file.job_stats %><br />

  <br />

  <div class="container_with_scroll">
    <table class="table is-bordered if-fullwidth is-striped is-hoverable">
      <thead>
      <%- @headers.each do |attr|%>
        <th><%= attr %></th>
      <%- end %>
      </thead>
      <tbody>
      <%- @records.each do |record| %>
        <tr>
          <%- @headers.each do |attr|%>
            <td><%= record[attr.to_s] %></td>
          <%- end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
</section>

app/views/file_uploads/upload.html.erb
<section class="px-6 py-12">
  <div class="container">
    <h1 class="text-title3 mb-4">File Upload(s)</h1>
    <p class="mb-4">
      <%= link_to "Upload More Files", new_file_upload_path,
          class: "bg-blue-600 border border-transparent cursor-pointer px-4 py-1 rounded text-white" %>
      <%= link_to "View All Files", file_uploads_path,
          class: "bg-blue-600 border border-transparent cursor-pointer px-4 py-1 rounded text-white" %>
    </p>
    <% @file_uploads.each do |file_upload| %>
      <p>
        <b><%= file_upload.result_message %></b><br />
        Category: <%= file_upload.category %><br />
        Filename: <%= file_upload.filename %><br />
      </p>
    <% end %>
  </div>
</section>