config/routes.rb
Rails.application.routes.draw do
  resources :exit_types
  devise_for :users, path_prefix: 'app'
  resources :users

  resources :passwords, only: [:edit, :update]
  resources :facilities do
    resources :locations
  end
  resources :cohorts
  resources :cohort_imports, only: [:create, :new]
  resources :measurement_types
  resources :animals do
    collection do
      get '/csv_upload', action: 'csv_upload'
      post '/csv_upload', action: 'import'
    end
  end
  resources :enclosures do
    collection do
      get '/csv_upload', action: 'csv_upload'
      post '/csv_upload', action: 'import'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :measurements
  post '/file_uploads', to: 'file_uploads#upload'
  resources :file_uploads, only: [:index, :new, :destroy]
  get '/file_uploads/csv_index', to: 'file_uploads#csv_index', as: 'csv_index'
  get '/file_uploads/:id', to: 'file_uploads#show', as: 'show_processed_file'

  get '/file_uploads/errors/:id', to: 'file_uploads#show_processing_csv_errors', as: 'show_processing_csv_errors'

  # resources :reports, only: [:index] # Replaced by blazer reporting - 1/24/21

  resources :operations, only: [:index]

  get 'home', action: 'index', controller: 'home'
  get 'about', action: 'show', controller: 'home'

  # mount ReportsKit::Engine, at: '/' # Replaced by blazer reporting - 1/24/21

  authenticate :user do
    mount Blazer::Engine, at: "blazer", as: 'reports'
  end

  root 'home#index'
end

app/models/enclosure.rb
class Enclosure < ApplicationRecord
  has_paper_trail

  include OrganizationScope
  include CsvExportable

  belongs_to :location, optional: true
  has_many :operations, dependent: :destroy
  has_many :measurements, as: :subject

  has_one :cohort, required: false

  validates :name, uniqueness: { scope: %i[organization_id location_id] }

  delegate :name, to: :location, prefix: true, allow_nil: true
  delegate :facility_name, to: :location, allow_nil: true
  delegate :facility_code, to: :location, allow_nil: true

  def self.exportable_columns
    column_names.reject { |col| %w[organization_id facility_id].include? col }.insert(2, 'facility_name')
  end

  def empty?
    cohort.blank?
  end
end

app/controllers/enclosures_controller.rb
class EnclosuresController < ApplicationController
  before_action :set_locations, only: %i[new edit]
  load_and_authorize_resource

  def index
    @enclosures = Enclosure.for_organization(current_organization).includes(location: :facility)

    respond_to do |format|
      format.html
      format.csv { send_data @enclosures.to_csv, filename: "#{Date.today.iso8601}-enclosures.csv" }
    end
  end

  def show; end

  def new
    @enclosure = Enclosure.new
  end

  def create
    @enclosure = Enclosure.new(enclosure_params)

    if @enclosure.save
      redirect_to enclosure_path(@enclosure), notice: 'Enclosure was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @enclosure.update(enclosure_params)
      redirect_to enclosure_path(@enclosure), notice: 'Enclosure was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @enclosure.destroy
    redirect_to enclosures_url, notice: 'Enclosure was successfully destroyed.'
  end

  def csv_upload; end

  def import
    if params[:enclosure_csv].content_type == 'text/csv'
      upload = FileUpload.create(user: current_user, organization: current_organization, status: 'Pending',
                                 file: params[:enclosure_csv])

      ImportEnclosuresJob.perform_later(upload)

      redirect_to enclosures_path, notice: 'Processing file...'
    else
      redirect_to csv_upload_enclosures_path, error: 'Invalid file type. Please upload a CSV.'
    end
  end

  private

  def enclosure_params
    params.require(:enclosure).permit(:location_id, :name).merge(organization_id: current_organization.id)
  end

  def set_locations
    @locations = Location.for_organization(current_user.organization).sort_by do |location|
      location.name_with_facility.downcase
    end
  end
end

app/views/enclosures/_form.html.erb
<%= form_with(model: enclosure, local: true, html: { class: "w-full" }) do |form| %>
  <% if enclosure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enclosure.errors.count, "error") %> prohibited this enclosure from being saved:</h2>

      <ul>
      <% enclosure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div>
      <%= form.label :location_id, class: 'text-sm text-caption-light font-medium uppercase' %>
    </div>
    <div>
      <%= form.collection_select :location_id, @locations, :id, :name_with_facility, { include_blank: 'Select Location' }, { class: 'input w-full mb-2' }  %>
    </div>
  </div>

  <div>
    <div>
      <%= form.label :name, class: 'text-sm text-caption-light font-medium uppercase' %>
    </div>
    <div>
      <%= form.text_field :name, class: 'input w-full mb-2' %>
    </div>
  </div>

  <div>
    <div>
      <%= form.submit('Submit', class: 'bg-primary-dark hover:bg-primary text-white font-bold py-2 px-4 rounded inline-flex items-center mt-4') %>
    </div>
  </div>
<% end %>

app/views/enclosures/csv_upload.html.erb
<section class="section facilities__form">
  <div class="container facilities__form__container">
    <h1 class="text-title3 mb-4">Upload Enclosures</h1>
    <div class="facilities__form__container__body">
      <%= link_to 'Click here', root_path + 'samples/enclosure.csv' %> for a sample csv file.
    </div>
    <div class="facilities__form__container__body">
      <%= link_to 'Click here', facilities_path %> to view facilities codes and location names.
    </div>

    <div class="facilities__form__container__body">
      <%= form_with(local: true) do |form| %>
        <div class="field">
          <%= form.file_field :enclosure_csv, required: true, accept: 'text/csv' %>
        </div>

        <div class="field">
          <div class="control">
            <%= form.submit('Submit', class: 'button-primary') %>
          </div>
        </div>
      <% end %>
    </div>

    <%= link_to '<< Back', enclosures_path, class: 'button-outline-primary' %>
  </div>
</section>

app/views/enclosures/edit.html.erb
<section class="h-screen p-12 bg-background">
  <div class="container px-8 py-6 mx-auto bg-white lg:max-w-xl rounded-md shadow-sm">
    <%= link_to enclosures_path, class: "inline-flex items-center py-2 mb-4 font-bold rounded text-primary-dark hover:text-primary" do %>
      <span><< Cancel</span>
    <% end %>
    <h1 class="text-title3 mb-4">Editing Enclosure</h1>
    <div class="relative block">
      <%= render 'form', enclosure: @enclosure %>
    </div>
  </div>
</section>

app/views/enclosures/index.html.erb
<section class="h-screen bg-background md:p-12 sm:w-100 p-0">
  <div class="container px-8 py-6 mx-auto bg-white rounded-md shadow-sm">
    <p id="notice"><%= notice %></p>
    <div class="flex md:flex-row flex-col md:justify-between mb-4">
      <h1 class="text-title2 text-center">Enclosures</h1>
      <div class="flex items-center justify-center">
        <%= link_to new_enclosure_path do %>
          <button class="bg-primary-dark hover:bg-primary text-white font-bold py-2 px-4 rounded inline-flex items-center mr-4">
            <%= image_tag  "icons/plus.png", size: 17 %>
            <span class="ml-2 hidden md:block">New Enclosure</span>
            <span class="ml-2 md:hidden">New</span>
          </button>  
        <% end %>
        <%= link_to csv_upload_enclosures_path do %>
          <button class="bg-primary-dark hover:bg-primary text-white font-bold py-2 px-4 rounded inline-flex items-center mr-4">
            <%= image_tag  "icons/plus.png", size: 17 %>
            <span class="ml-2 hidden md:block">Upload CSV</span>
            <span class="ml-2 md:hidden">Upload</span>
          </button>   
        <% end %>
        <%= link_to enclosures_path(format: :csv), id: "export_button" do %>
          <button class="bg-primary-dark hover:bg-primary text-white font-bold py-2 px-4 rounded inline-flex items-center mr-4">
            <span class="ml-2 hidden md:block">Export to CSV</span>
            <span class="ml-2 md:hidden">Export</span>
          </button>   
        <% end %>
      </div>
    </div>
    <table class="w-full border table-auto">
      <thead>
        <tr class="border">
          <th class="px-4 py-2 text-sm font-medium uppercase text-caption-light" scope="col">Name</th>
          <th class="px-4 py-2 text-sm font-medium uppercase text-caption-light" scope="col">Facility</th>
          <th class="px-4 py-2 text-sm font-medium uppercase text-caption-light" scope="col">Location</th>
          <th class="px-4 py-2 text-sm font-medium uppercase text-caption-light" scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @enclosures.each do |enclosure| %>
          <tr>
            <td class="px-4 py-2" data-label="Name"><%= enclosure.name %></td>
            <td class="px-4 py-2" data-label="Facility"><%= enclosure.facility_name %></td>
            <td class="px-4 py-2" data-label="Location"><%= enclosure.location_name %></td>
            <td class="text-base px-4 py-2 align-middle flex items-center"  data-label="Actions"><%= link_to 'Show', enclosure, 'aria-label': "Show #{enclosure.name}", class: 'text-primary-dark' %> <%= link_to image_tag("icons/edit.svg"), edit_enclosure_path(enclosure), 'aria-label': "Edit #{enclosure.name}", class: 'w-5 mx-2' %> <%= link_to image_tag("icons/trash.svg"), enclosure, 'aria-label': "Delete #{enclosure.name}", method: :delete, data: { confirm: 'Are you sure?' }, class: 'w-5 mx-2' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/enclosures/new.html.erb
<section class="h-screen p-12 bg-background">
  <div class="container px-8 py-6 mx-auto bg-white lg:max-w-xl rounded-md shadow-sm">
    <%= link_to enclosures_path, class: "inline-flex items-center py-2 mb-4 font-bold rounded text-primary-dark hover:text-primary" do %>
      <span><< Cancel</span>
    <% end %>
    <h1 class="text-title3 mb-4">New Enclosure</h1>
    <div>
      <%= render 'form', enclosure: @enclosure %>
    </div>
  </div>
</section>

app/views/enclosures/show.html.erb
<section class="h-screen p-12 bg-background">
  <div class="container px-8 py-6 mx-auto bg-white lg:max-w-xl rounded-md shadow-sm">
    <p id="notice"><%= notice %></p>
    <div class="flex items-start justify-between mb-4">
      <%= link_to enclosures_path, class: "inline-flex items-center py-2 font-bold rounded text-primary-dark hover:text-primary" do %>
        <span><< Back</span>
      <% end %>
      <%= link_to edit_enclosure_path(@enclosure), class: "inline-flex items-center px-4 py-2 font-bold text-white rounded bg-primary-dark hover:bg-primary" do %>
        <span>Edit Enclosure</span>
      <% end %>
    </div>
    <div>
      <h1 class="text-title3 mb-4">Enclosure</h1>
    </div>
    <div class="block">
        <div class="text-sm font-medium uppercase text-caption-light">Name</div>
        <%= @enclosure.name %>
        <div class="mt-2 text-sm font-medium uppercase text-caption-light">Facility</div>
        <%= @enclosure.facility_name %>
        <div class="mt-2 text-sm font-medium uppercase text-caption-light">Location</div>
        <%= @enclosure.location_name %>
    </div>

    <%= link_to '<< BACK', enclosures_path, class: "mr-3 mb-3 button-outline-primary" %>
    <%= link_to "Edit", edit_enclosure_path(@enclosure), class: "button-outline-primary mt-4" %>

  </div>
</section>