config/routes.rb
Rails.application.routes.draw do
  resources :exit_types
  devise_for :users, path_prefix: 'app'
  resources :users

  resources :passwords, only: [:edit, :update]
  resources :facilities do
    resources :locations
  end
  resources :cohorts
  resources :cohort_imports, only: [:create, :new]
  resources :measurement_types
  resources :animals do
    collection do
      get '/csv_upload', action: 'csv_upload'
      post '/csv_upload', action: 'import'
    end
  end
  resources :enclosures do
    collection do
      get '/csv_upload', action: 'csv_upload'
      post '/csv_upload', action: 'import'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :measurements
  post '/file_uploads', to: 'file_uploads#upload'
  resources :file_uploads, only: [:index, :new, :destroy]
  get '/file_uploads/csv_index', to: 'file_uploads#csv_index', as: 'csv_index'
  get '/file_uploads/:id', to: 'file_uploads#show', as: 'show_processed_file'

  get '/file_uploads/errors/:id', to: 'file_uploads#show_processing_csv_errors', as: 'show_processing_csv_errors'

  # resources :reports, only: [:index] # Replaced by blazer reporting - 1/24/21

  resources :operations, only: [:index]

  get 'home', action: 'index', controller: 'home'
  get 'about', action: 'show', controller: 'home'

  # mount ReportsKit::Engine, at: '/' # Replaced by blazer reporting - 1/24/21

  authenticate :user do
    mount Blazer::Engine, at: "blazer", as: 'reports'
  end

  root 'home#index'
end

app/controllers/home_controller.rb
require 'yaml'

class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    return unless current_user

    translate_yaml()

    # Retrive current organization stats
    @facility_count = current_user.organization.facilities.count
    @cohort_count = current_user.organization.cohorts.count
    @animal_count = current_user.organization.animals.count
  end

  def show; end

  def encode(msg)
    msg.to_yaml
  end

  def decode(str)
    YAML.load(str)
  end

  def translate_yaml
    obj = {
      name: "Tiffany Mitchell",
      quantity: 1_000_000,
      addresses: {
        address1: "12 Heather Street, Parnell, Auckland, New Zealand",
        address2: "1 Queen Street, CBD, Auckland, New Zealand"
      }
    }

    samples = 50_000
    samples.times do
      decode(encode(obj))
    end
  end
end

app/views/home/_bottom_content.html.erb
<div class="bottom_content">
    <div class="container flex flex-wrap">
      <div class="bottom_content_container">
        <span class="text-title2 text-center pb-4">Github Repo</span>
        <p class="pb-5">
          If you'd like to contribute, check out our github repo or consider
          donating to the <a href="https://give.ucdavis.edu/BOML/BMLABAL">Endangered
          White Abalone Restoration Fund</a>.
        </p>
       <a href="https://github.com/rubyforgood/abalone" target="_blank" tabindex=18> <button class="button-primary"> Contribute </button> </a>
      </div>
      <div class="bottom_content_container">
        <span class="text-title2 text-center">Links</span>
          <div class="content">
            <ul>
              <li>
                <a href="https://marinescience.ucdavis.edu/research-programs/conservation/saving-white-abalone">
                  UC Davis - Saving White Abalone
                </a>
              </li>
              <li>
                <a href="https://youtu.be/kXGv5pwZ29o">Bodega Marine Lab - Delicacy of
                  the Deep, Saving White Abalone
                </a>
              </li>
              <li>
                <a href="https://www.youtube.com/watch?v=B-FiDUIY6aQ&feature=youtu.be">
                  360 Video: UC Davis Working to Save White Abalone
                </a>
              </li>
              <li>
                <a href="https://www.biographic.com/posts/sto/fighting-for-a-foothold">
                  Fighting For a Foothold
                </a>
              </li>
              <li>
                <a href="https://www.facebook.com/whiteabalone/">Facebook</a>
              </li>
              <li>
                <a href="https://www.instagram.com/white_abalone/">Instagram</a>
              </li>
              <li>
                <a href="https://twitter.com/whiteabalone">Twitter</a>
              </li>
            </ul>
          </div>
      </div>
    </div>
  </div> 

app/views/home/_footer.html.erb
<div class="footer">
  <span>
    The Abalone Analytics app was lovingly built by:<a href="https://rubyforgood.org/" target="_blank" tabindex=18>Ruby for Good</a>
  </span>
</div>

app/views/home/_hero.html.erb
<section class="hero py-50">
    <div class="container hero-container">
        <div class="hero-left">
            <h1 class="font-semibold hero-title pb-5">Abalone Analytics</h1>
            <h3 class="hero-subtitle pb-2">About The Project</h3>
            <p>The Bodega Marine Laboratory's White Abalone captive breeding program is
      working to prevent the extinction of the White Abalone (<a
      href="https://en.wikipedia.org/wiki/Haliotis_sorenseni" style="color: white !important; text-decoration: underline;">Haliotis
      sorenseni</a>), an endangered marine snail.  White abalone are one of
      seven species found in California and are culturally significant to the
      native people of the area.  White abalone were perilously overfished
      throughout the 20th century, resulting in a 99 percent population decrease
      by the end of the 1970s.  This group is working to reverse their decline
      and have already seen some great success, they currently have more abalone
      in the lab than exist in the wild!  Ruby for Good is supporting these
      efforts by developing a data tracking and analytics system for Abalone
      population trends, mortality rates, and breeding programs to help save
      this species from extinction. </p>
        </div>
    </div>
</section>

app/views/home/index.html.erb
<%= render :partial => 'hero' %>

<% if current_user %>
  <div class="flex flex-row p-3"></div>
  <section class="block">
    <h2 class="break-words font-semibold text-title2 text-center">
      Your organization: <%= current_organization.name %>
    </h2>
  </section>
  <div class="flex justify-content-center flex-wrap container">
    <div class="dashboard-cards">
      <p class="break-words font-normal text-title4">Total No. of Animals<br />
        <span class="text-title2 text-center"><%= @animal_count %></span>
      </p>
      <button class="mt-5">
        <%= link_to 'View All Animals', animals_path, class: 'white-btn' %>
      </button>
    </div>
    <div class="dashboard-cards">
      <p class="break-words font-normal text-title4">Number of Facilities<br />
        <span class="text-title2 text-center"><%= @facility_count %></span>
      </p>
      <button class="mt-5">
        <%= link_to 'View All Facilities', facilities_path, class: 'white-btn' %>
      </button>
    </div>
    <div class="dashboard-cards">
      <p class="break-words font-normal text-title4">Number of Cohorts<br />
        <span class="text-title2 text-center"><%= @cohort_count %></span>
      </p>
      <button class="mt-5">
        <%= link_to 'View All Cohorts', cohorts_path, class: 'white-btn' %>
      </button>
    </div>
  </div>
<% end %>
<%= render :partial => 'bottom_content' %>
<%= render :partial => 'footer' %>

app/views/home/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="text-title2">About the Project!!!</h1>
    <p>
      The Bodega Marine Laboratory's White Abalone captive breeding program is
      working to prevent the extinction of the White Abalone (<a
      href="https://en.wikipedia.org/wiki/Haliotis_sorenseni">Haliotis
      sorenseni</a>), an endangered marine snail.  White abalone are one of
      seven species found in California and are culturally significant to the
      native people of the area.  White abalone were perilously overfished
      throughout the 20th century, resulting in a 99 percent population decrease
      by the end of the 1970s.  This group is working to reverse their decline
      and have already seen some great success, they currently have more abalone
      in the lab than exist in the wild!  Ruby for Good is supporting these
      efforts by developing a data tracking and analytics system for Abalone
      population trends, mortality rates, and breeding programs to help save
      this species from extinction.
    </p>
  </div>
</section>
<section class="section">
  <div class="container content">
    <h2 class="title is-5">Links</h2>
    <ul>
      <li>
        <a href="https://marinescience.ucdavis.edu/research-programs/conservation/saving-white-abalone">
          UC Davis - Saving White Abalone
        </a>
      </li>
      <li>
        <a href="https://youtu.be/kXGv5pwZ29o">Bodega Marine Lab - Delicacy of
          the Deep, Saving White Abalone
        </a>
      </li>
      <li>
        <a href="https://www.youtube.com/watch?v=B-FiDUIY6aQ&feature=youtu.be">
          360 Video: UC Davis Working to Save White Abalone
        </a>
      </li>
      <li>
        <a href="https://www.biographic.com/posts/sto/fighting-for-a-foothold">
          Fighting For a Foothold
        </a>
      </li>
      <li>
        <a href="https://www.facebook.com/whiteabalone/">Facebook</a>
      </li>
      <li>
        <a href="https://www.instagram.com/white_abalone/">Instagram</a>
      </li>
      <li>
        <a href="https://twitter.com/whiteabalone">Twitter</a>
      </li>

    </ul>
  </div>
</section>
<section class="section">
  <div class="container">
    <h2 class="title is-5">Contribute</h2>
    <p>
      If you'd like to contribute, check out our <a
      href="https://github.com/rubyforgood/abalone">github repo</a> or consider
      donating to the <a href="https://give.ucdavis.edu/BOML/BMLABAL">Endangered
      White Abalone Restoration Fund</a>.
    </p>
  </div>
</section>